#!/usr/bin/env bash

SCRIPT_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)
# shellcheck source=../bin/lib/env
source "$SCRIPT_ROOT/../bin/lib/env"

execute_dir=$(pwd)
echo "$execute_dir"

options=$(getopt \
  --options "" \
  --longoptions help,install-path:,aws-codebuild-image-name:,aws-codebuild-image-sha: \
  -- "$@")
eval set --"$options"

INVALID="INVALID"
INSTALL_PATH="$INVALID"
AWS_CODEBUILD_IMAGE_NAME="amazon/aws-codebuild-local"
AWS_CODEBUILD_IMAGE_SHA="948390fe21cd700f7c8b8c64ee89faf7aeca8ab87cd9dac4ba6c853a35817ae3"


info() {
  echo "Installs the codebuild_build.sh script with dependencies"
	echo "makes you able to run aws codebuild locally :)"
}

usage() {
  echo "Usage: $0 --install-path=<path/to/codebuild_local/folder>"
  echo -e "\t--help"
	echo -e "\t\tprints this message"
	echo -e "\t--install-path=<path>"
	echo -e "\t\t is the path where you want the codebuild_build.sh script installed. (NO DEFAULT)"
  echo -e "\t--aws-codebuild-image-name"
	echo -e "\t\tname of the codebuild docker image (default: $AWS_CODEBUILD_IMAGE_NAME )"
  echo -e "\t--aws-codebuild-image-sha"
	echo -e "\t\tthe sha of the codebuild docker image you want (default: $AWS_CODEBUILD_IMAGE_SHA )"
  exit 1
}

while true; do
  case "$1" in
  --install-path)
    shift
    INSTALL_PATH="$1"
    ;;
  --help)
		info
		echo ""
    usage
    exit 1
    ;;
  --)
    shift
    break
    ;;
  esac
  shift
done

if [[ "$INSTALL_PATH" == "$INVALID" ]]; then
	echo "Need an install path"
	echo ""
	usage
	exit 1
fi

validate_docker_image() {
	image="$1"
	sha256="$2"
	aws_codebuild_expected_sha256="$sha256"
	actual_sha256=$(docker inspect --format='{{index .RepoDigests 0}}' "$image" | sed 's/amazon\/aws-codebuild-local@sha256://')

	if [[ "$aws_codebuild_expected_sha256" != "$actual_sha256" ]]; then
		echo "Faulty sha256 from amazon/aws-codebuild-local image"
		exit 1
	else
		echo "amazon/aws-codebuild-local image passed the sha256 test"
	fi
}


# shellcheck source=../bin/lib/unique/unique.sh
source "$LIB_ROOT/unique/unique.sh"

TMP_NAME="/tmp/aws-codebuild-local-install"
TMP_DIR="$(unique-postfix "$TMP_NAME")"
mkdir -p "$TMP_DIR"
cd "$TMP_DIR" || exit
echo "working in $TMP_DIR"


#Setup build image
git clone https://github.com/aws/aws-codebuild-docker-images.git
docker build -t aws/codebuild/standard:4.0 aws-codebuild-docker-images/ubuntu/standard/4.0

#Install local CodeBuild agent
docker pull amazon/aws-codebuild-local:latest --disable-content-trust=false
validate_docker_image "$AWS_CODEBUILD_IMAGE_NAME" "$AWS_CODEBUILD_IMAGE_SHA"


#Install codebuild
wget https://raw.githubusercontent.com/aws/aws-codebuild-docker-images/master/local_builds/codebuild_build.sh
chmod +x codebuild_build.sh

MV_PATH=""
if [[ "${INSTALL_PATH:0:1}" = "/" ]]; then
	#Absolute path
	MV_PATH="$INSTALL_PATH"
else
	MV_PATH="$execute_dir/$INSTALL_PATH"
fi

install_command="mv codebuild_build.sh $MV_PATH"
echo "$install_command"
eval "$install_command"

