#!/usr/bin/env bash

SCRIPT_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)
# shellcheck source=../bin/lib/env
source "$SCRIPT_ROOT/../bin/lib/env"

# shellcheck source=../bin/lib/log/log.sh
source "$LIB_ROOT/log/log.sh"

log_info "running linter on all bash files in the repo"
log_info "Searching for all the bash files in repo..." 1
find "$PROJECT_ROOT" -type f \
-path "$PROJECT_ROOT/.git*" -prune -o \
-path "$PROJECT_ROOT/backups*" -prune -o \
-exec bash -c '[[ "$( file -bi "$1" )" == */x-shellscript* ]]' bash {} ';' \
-print \
| tr '\012' ' ' \
| ( 
	mapfile -d ' ' -t bash_files; 
	log_info "running shellcheck" 1
	if shellcheck -x -P SCRIPTDIR "${bash_files[@]}"; then
		log_success "Bash linting passed!" 1
		exit 0
	else
		log_fail "Bash linting did not pass" 1
		exit 1
	fi
)


