#!/usr/bin/env bash

SCRIPT_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)
# shellcheck source=../bin/lib/env
source "$SCRIPT_ROOT/../bin/lib/env"
# shellcheck source=../bin/lib/log/log.sh
source "$LIB_ROOT/log/log.sh"

log_info "running linter on nvim configs"
"$PROJECT_ROOT/dev-bin/nvim-config-lint"
