#!/usr/bin/env bash

SCRIPT_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)
# shellcheck source=../bin/lib/env
source "$SCRIPT_ROOT/../bin/lib/env"

"$PROJECT_ROOT/dev-bin/nvim-config-lint"

"$PROJECT_ROOT/dev-bin/bash-lint"
