#!/usr/bin/env bash

SCRIPT_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)
# shellcheck source=../bin/lib/env
source "$SCRIPT_ROOT/../bin/lib/env"

# shellcheck source=../bin/lib/log/log.sh
source "$LIB_ROOT/log/log.sh"

log_info "running linter on nvim configs"
# shellcheck source=../bin/lib/lintvim/lintvim.sh
source "$LIB_ROOT/lintvim/lintvim.sh"
lintvim "$PROJECT_ROOT/.config/nvim"

exit_code="$?"
if [[ "$exit_code" -eq 0 ]]; then 
	log_success "nvim config files linted great" 1
else
	log_fail "nvim configs did not pass the linting" 1
fi

exit "$exit_code" #Passing along the error code
